src/aspCart.Web/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using aspCart.Web.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using aspCart.Core.Interface.Services.Catalog;
using aspCart.Core.Interface.Services.User;
using aspCart.Core.Interface.Services.Sale;
using Microsoft.AspNetCore.Authorization;
using aspCart.Core.Domain.User;
using AutoMapper;
using aspCart.Infrastructure.EFModels;
using Microsoft.AspNetCore.Identity;
using aspCart.Core.Domain.Sale;

namespace aspCart.Web.Controllers
{
    public class CartController : Controller
    {
        #region Fields

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IProductService _productService;
        private readonly IBillingAddressService _billingAddressService;
        private readonly IOrderService _orderService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IMapper _mapper;

        private ISession Session => _httpContextAccessor.HttpContext.Session;
        private readonly string _cartItesmSessionKey = "CartItems";
        private readonly string _cartItemsCountSessionKey = "CartItemsCount";

        #endregion

        #region Constructor

        public CartController(
            UserManager<ApplicationUser> userManager,
            IProductService productService,
            IBillingAddressService billingAddressService,
            IOrderService orderService,
            IHttpContextAccessor httpContextAccessor,
            IMapper mapper)
        {
            _userManager = userManager;
            _productService = productService;
            _billingAddressService = billingAddressService;
            _orderService = orderService;
            _mapper = mapper;
            _httpContextAccessor = httpContextAccessor;
        }

        #endregion

        #region Methods

        // GET: /Cart/
        public IActionResult Index()
        {
            var cartItems = new List<CartItemModel>();

            if (Session.GetString(_cartItesmSessionKey) != null)
                cartItems = JsonConvert.DeserializeObject<List<CartItemModel>>(Session.GetString(_cartItesmSessionKey));

            return View(cartItems);
        }

        // POST: /Cart/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(Guid id)
        {
            if(id == null)
                return RedirectToAction("Index");

            // check if product exist
            var selectedItem = _productService.GetProductById(id);
            if(selectedItem == null)
                return RedirectToAction("Index");

            // check if there are already cart instance
            var cartItems = new List<CartItemModel>();
            if (Session.GetString(_cartItesmSessionKey) != null)
                cartItems = JsonConvert.DeserializeObject<List<CartItemModel>>(Session.GetString(_cartItesmSessionKey));

            // check if the item are already in the cart
            // if the item is already in the cart,
            // increase the quantity by 1
            if (cartItems.Exists(x => x.Id == selectedItem.Id))
                cartItems.Find(x => x.Id == selectedItem.Id).Quantity++;
            else
            {
                var item = new CartItemModel
                {
                    Id = selectedItem.Id,
                    Name = selectedItem.Name,
                    Price = selectedItem.Price,
                    Quantity = 1,
                    MaxCartQuantity = selectedItem.MaximumCartQuantity,
                    SeoUrl = selectedItem.SeoUrl
                };

                // check for discount
                if (selectedItem.SpecialPriceEndDate != null && selectedItem.SpecialPriceEndDate >= DateTime.Now)
                {
                    item.OldPrice = selectedItem.Price;
                    item.Price = selectedItem.SpecialPrice ?? item.OldPrice;
                }

                if (selectedItem.Images.Count > 0)
                {
                    item.MainImage = selectedItem.Images
                        .OrderBy(x => x.SortOrder)
                        .ThenBy(x => x.Position)
                        .FirstOrDefault()
                        .Image
                        .FileName;
                }

                cartItems.Add(item);
            }

            // add to session
            Session.SetString(_cartItesmSessionKey, JsonConvert.SerializeObject(cartItems));
            Session.SetInt32(_cartItemsCountSessionKey, cartItems.Count());

            return RedirectToAction("Index");
        }

        // GET: /Cart/Save
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save(List<string> ids, List<string> quantity)
        {
            var cartItems = new List<CartItemModel>();

            for (int i = 0; i < ids.Count; i++)
            {
                int qty = Convert.ToInt32(Math.Floor(Convert.ToDouble(quantity[i])));
                if (qty == 0)
                    continue;

                Guid id;
                if (Guid.TryParse(ids[i], out id))
                {
                    // check if id is valid
                    var item = _productService.GetProductById(id);
                    if(item != null)
                    {
                        var newCartItem = new CartItemModel
                        {
                            Id = item.Id,
                            Name = item.Name,
                            Price = item.Price,
                            Quantity = qty,
                            MaxCartQuantity = item.MaximumCartQuantity,
                            SeoUrl = item.SeoUrl
                        };

                        // check for discount
                        if (item.SpecialPriceEndDate != null && item.SpecialPriceEndDate >= DateTime.Now)
                        {
                            newCartItem.OldPrice = item.Price;
                            newCartItem.Price = item.SpecialPrice ?? newCartItem.OldPrice;
                        }

                        if (item.Images.Count > 0)
                        {
                            newCartItem.MainImage = item.Images
                                .OrderBy(x => x.SortOrder)
                                .ThenBy(x => x.Position)
                                .FirstOrDefault()
                                .Image
                                .FileName;
                        }

                        cartItems.Add(newCartItem);
                    }
                }
            }

            // add or remove sesion
            if(cartItems.Count > 0)
            {
                Session.SetString(_cartItesmSessionKey, JsonConvert.SerializeObject(cartItems));
                Session.SetInt32(_cartItemsCountSessionKey, cartItems.Count());
            }
            else
            {
                Session.Remove(_cartItesmSessionKey);
                Session.Remove(_cartItemsCountSessionKey);
            }

            return RedirectToAction("Index");
        }

        // GET: /Cart/Checkout
        [Authorize]
        public async Task<IActionResult> Checkout()
        {
            if (Session.GetString(_cartItesmSessionKey) == null)
                return View("Index");

            var user = await GetCurrentUserAsync();
            var checkoutModel = new CheckoutModel();
            var cartItems = JsonConvert.DeserializeObject<List<CartItemModel>>(Session.GetString(_cartItesmSessionKey));
            var billingAdddressEntity = _billingAddressService.GetBillingAddressById(user.BillingAddressId);
            if (billingAdddressEntity != null)
            {
                Session.SetString("BillingAddress", JsonConvert.SerializeObject(billingAdddressEntity));
                ViewData["BillingAddress"] = true;
            }

            checkoutModel.CartItemModel = cartItems;

            return View(checkoutModel);
        }

        // POST: /Cart/Checkout
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Checkout(CheckoutModel model)
        {
            // get current user
            var user = await GetCurrentUserAsync();
            var totalOrderPrice = 0m;

            // create order entity 
            var orderEntity = new Order
            {
                Id = Guid.NewGuid(),
                OrderNumber = GenerateUniqueOrderNumber(),
                UserId = Guid.Parse(user.Id),
                Status = OrderStatus.Pending,
                OrderPlacementDateTime = DateTime.Now
            };

            var orderItemEntities = new List<OrderItem>();
            var cartItems = new List<CartItemModel>();

            // get cart session
            if (Session.GetString(_cartItesmSessionKey) != null)
                cartItems = JsonConvert.DeserializeObject<List<CartItemModel>>(Session.GetString(_cartItesmSessionKey));

            foreach(var item in cartItems)
            {
                var currentItem = _productService.GetProductById(item.Id);
                if(currentItem != null)
                {
                    var newOrderItem = new OrderItem
                    {
                        Id = Guid.NewGuid(),
                        OrderId = orderEntity.Id,
                        ProductId = item.Id.ToString(),
                        Name = item.Name,
                        Quantity = item.Quantity,
                        Price = item.Price,
                        TotalPrice = (item.Price * item.Quantity)
                    };

                    orderItemEntities.Add(newOrderItem);
                    totalOrderPrice += newOrderItem.TotalPrice;
                }
            }

            // check if the order have item/s
            if (orderItemEntities.Count > 0)
            {

src/aspCart.Web/ViewComponents/FilterViewComponent.cs
using aspCart.Core.Interface.Services.Catalog;
using aspCart.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace aspCart.Web.ViewComponents
{
    [ViewComponent(Name = "Filter")]
    public class FilterViewComponent : ViewComponent
    {
        #region Fields

        private readonly ICategoryService _categoryService;
        private readonly IManufacturerService _manufacturerService;
        private readonly IProductService _productService;

        #endregion

        #region Constructor

        public FilterViewComponent(
            ICategoryService categoryService,
            IManufacturerService manufacturerService,
            IProductService productService)
        {
            _categoryService = categoryService;
            _manufacturerService = manufacturerService;
            _productService = productService;
        }

        #endregion

        #region Methods

        public IViewComponentResult Invoke(string nameFilter = "", string categoryFilter = "", string manufacturerFilter = "" )
        {
            //
            // category filter
            //

            var categoryFilterViewModel = new List<CategoryFilterViewModel>();

            var allCategories = _categoryService.GetAllCategoriesWithoutParent();

            foreach(var category in allCategories)
            {
                var filterModel = new CategoryFilterViewModel { Name = category.Name, Id = category.Id };
                var qty = 0;

                if(nameFilter.Length > 0)
                {
                    qty = filterModel.Quantity = _productService.Table()
                        .Include(x => x.Categories).ThenInclude(x => x.Category)
                        .Where(x => x.Name.ToLower().Contains(nameFilter.ToLower()))
                        .Where(x => x.Categories.Any(c => c.Category.SeoUrl.ToLower() == category.SeoUrl.ToLower()))
                        .Where(x => x.Published == true)
                        .AsNoTracking()
                        .Count();
                }
                if(manufacturerFilter.Length > 0)
                {
                    qty = filterModel.Quantity = _productService.Table()
                        .Include(x => x.Categories).ThenInclude(x => x.Category)
                        .Include(x => x.Manufacturers).ThenInclude(x => x.Manufacturer)
                        .Where(x => x.Manufacturers.Any(m => m.Manufacturer.Name.ToLower() == manufacturerFilter.ToLower()))
                        .Where(x => x.Categories.Any(c => c.Category.SeoUrl.ToLower() == category.SeoUrl.ToLower()))
                        .Where(x => x.Published == true)
                        .AsNoTracking()
                        .Count();
                }

                if (qty > 0) { categoryFilterViewModel.Add(filterModel); }
            }

            //
            // manufacturer filter
            //

            var manufacturerFilterViewModel = new List<ManufacturerFilterViewModel>();

            var allManufacturer = _manufacturerService.GetAllManufacturers();

            foreach(var manufacturer in allManufacturer)
            {
                var filterModel = new ManufacturerFilterViewModel { Name = manufacturer.Name, Id = manufacturer.Id };
                var qty = 0;

                qty = filterModel.Quantity = _productService.Table()
                    .Include(x => x.Categories).ThenInclude(x => x.Category)
                    .Include(x => x.Manufacturers).ThenInclude(x => x.Manufacturer)
                    .Where(x => x.Manufacturers.Any(m => m.Manufacturer.Name.ToLower() == manufacturer.Name.ToLower()))
                    .Where(x => x.Categories.Any(c => c.Category.Name.ToLower() == categoryFilter.ToLower()))
                    .Where(x => x.Published == true)
                    .AsNoTracking()
                    .Count();

                if (qty > 0) { manufacturerFilterViewModel.Add(filterModel); }
            }

            //
            // price filter
            //

            var allProducts = _productService.Table()
                .Include(x => x.Categories).ThenInclude(x => x.Category)
                .Include(x => x.Manufacturers).ThenInclude(x => x.Manufacturer)
                .Where( x=> x.Published  == true)
                .AsNoTracking()
                .ToList();

            bool showPrice = false;

            if(nameFilter.Length > 0)
            {
                allProducts = allProducts
                    .Where(x => x.Name.ToLower().Contains(nameFilter.ToLower()))
                    .ToList();

                showPrice = true;
            }
            if(manufacturerFilter.Length > 0)
            {
                allProducts = allProducts
                    .Where(x => x.Manufacturers.Any(m => m.Manufacturer.Name.ToLower() == manufacturerFilter.ToLower()))
                    .ToList();

                showPrice = true;
            }
            if (categoryFilter.Length > 0)
            {
                allProducts = allProducts
                    .Where(x => x.Categories.Any(m => m.Category.Name.ToLower() == categoryFilter.ToLower()))
                    .ToList();

                showPrice = true;
            }

            List<int> range = new List<int>();
            List<IGrouping<int, decimal>> groupings = new List<IGrouping<int, decimal>>();
            List<decimal> allPrices = allProducts.Select(x => x.Price).ToList();

            if (showPrice)
            {
                range = new List<int> { 0, 100, 250, 500, 750, 1000, 1500, 2000, 3000, 4000, 5000, 10000 };
                groupings = allPrices.GroupBy(price => range.FirstOrDefault(r => r >= price)).ToList();
            }
           
            //
            // result
            //

            var result = new FilterViewModel();
            result.CategoryFilterViewModel = categoryFilterViewModel;
            result.ManufacturerFilterViewModel = manufacturerFilterViewModel;
            result.PriceGroupings = groupings.OrderBy(x => x.Key);
            result.PriceRange = range;

            if (nameFilter.Length > 0)
            {
                result.FilterType = "name";
                ViewData["name"] = nameFilter;
            }

            if (manufacturerFilter.Length > 0) { result.FilterType = "manufacturer"; }

            if (categoryFilter.Length > 0) { result.FilterType = "category"; }

            return View(result);
        }

        #endregion
    }
}

src/aspCart.Web/Views/Manufacturer/ManufacturerInfo.cshtml
@model IEnumerable<ProductModel>
@{
    ViewData["Title"] = ViewData["Manufacturer"];
}

<div class="row-side">
    <div class="left-nav">
        @await Component.InvokeAsync("Filter", new { manufacturerFilter = ViewData["Manufacturer"] })
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12">
                <h2 class="text-muted">@ViewData["Manufacturer"] product list</h2>
                <hr />
            </div>
        </div>
        <div class="row"> <!-- sorting place holder -->
            <div class="col-md-12">
                <form id="sortByForm">
                    <label>Sort by: </label>
                    <select id="sortBy">
                        <option id="Default" value="Default">Default</option>
                        <option id="LowestPrice" value="LowestPrice">Lowest Price</option>
                        <option id="HighestPrice" value="HighestPrice">Highest Price</option>
                        <option id="BestSelling" value="BestSelling" disabled>Best Selling</option>
                        <option id="MostReviews" value="MostReviews">Most Reviews</option>
                        <option id="NewestToOldest" value="NewestToOldest">Newest to Oldest</option>
                    </select>
                </form>
            </div>
        </div>
        <div class="row"> <!-- sort badge -->
            <div class="col-md-12">
                <div class="form-horizontal">
                    @foreach (var c in (List<string>)ViewData["SortKey"])
                    {
                        <span class="badge badge-info sort-key">
                            @c <span class="badge-delete" data-value="@c">x</span>
                        </span>
                    }
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 8px;"> <!-- main content -->
            @if (Model.Count() > 0)
            {
                @foreach (var product in Model)
                {
                    <div class="col-md-6 col-lg-4 col-xl-3">
                        <div class="card">
                            <center>
                                <a href="/Product/@product.SeoUrl">
                                    @if (product.MainImage != null)
                                    {
                                        <img class="card-img-top img-fluid" src="@product.MainImage" alt="@product.Name" />
                                    }
                                    else
                                    {
                                        <img class="card-img-top img-fluid" src="~/images/system/no-image.png" alt="@product.Name" />
                                    }
                                </a>
                            </center>
                            <div class="card-block">
                                <a href="/Product/@product.SeoUrl" class="card-title text-muted" title="@product.Name">@product.Name</a>
                                <div class="card-text">@product.Price.ToString("C2")</div>
                            </div>
                            <div class="card-footer">
                                <form asp-area="" asp-controller="Cart" asp-action="Add" method="post">
                                    <input type="hidden" value="@product.Id" name="id" />
                                    <button type="submit" id="addToCart" class="btn btn-primary btn-sm">Add to cart</button>
                                    @if (product.Rating > 0)
                                    {
                                        <div class="float-right">
                                            <i class="fa fa-star star-active"></i>
                                            <span>@product.Rating.ToString("N2")</span>
                                        </div>
                                    }
                                </form>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="col-md-12">
                    <h5>No product listing for this manufacturer</h5>
                </div>
            }
        </div>
    </div>
</div>

<script>
    // recheck all selected filters
    $(function () {
        let sortKey = @Json.Serialize(ViewData["SortKey"]);
        $.each(sortKey, function(index, value){
            $("[id='" + value + "']").prop('checked', true);
        });
    });

    $(function(){
        $('.badge-delete').on('click', function() {
            let idToDelete = $(this).data('value');
            $(this).parent().remove();
            $("[id='" + idToDelete + "']").prop('checked', false);
            $('#filterForm').submit(); // submit form from file Views/Shared/Components/Filter/Default.cshtml
        });
    });

    $(function(){
        let sortBy = '@(ViewData["SortBy"] == null ? "Default" : ViewData["SortBy"])';
        $('#' + sortBy).prop('selected', true);

        $('#sortBy').on('change', function(){
            $('#sortByFilter').val($(this).val());
            $('#filterForm').submit(); // submit form from file Views/Shared/Components/Filter/Default.cshtml
        });
    });
</script>